FROM hiyouga/llamafactory:latest

# Install Python packages
# RUN pip install bitsandbytes>=0.39.0 wandb 

# Print confirmation message during build
RUN echo "****************************************************" && \
    echo "Dockerfile running as expected" && \
    echo "****************************************************"

# Set working directory
WORKDIR /workspace

# Default command when container starts
CMD ["bash"]