services:
  llamafactory: 
    image: llm-to-rl
    stdin_open: true 
    build: . 
    tty: true 
    ipc: host 
    ports:
      - 8888:8888
    gpus: all 
    volumes: 
      - ./models:/app/models              # Model weights
      - ./cache:/root/.cache              # Cache
      - ./data:/app/data                  # Datasets
      - ./checkpoints:/app/checkpoints    # Training outputs